[package]
name = "beanstalk"
version = "0.1.0"
authors = ["Michael Chi <chicong@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
